### ISSUE TITLE
Project not building

### ISSUE THREAD

**Issue by moh1122** [AgoraLab/OpenVoiceCall_iOS#1]
Hello
Please note that the project is not building even after adding the agora framework.
I already run the project openVideoCall and its running normally, but with this project I got some errors: /OpenVoiceCall/OpenVoiceCall-Bridging-Header.h:5:9: 'AgoraAudioKit/AgoraRtcEngineKit.h' file not found
I already imported the framework.
Any clue, plz help?

**Comment by PRWrl** [comment]
Project OpenVideoCall use AgoraRtcEngineKit.framework while this project need AgoraAudioKit.framework which is an audio only sdk.
